### ISSUE TITLE
Nudging files

### ISSUE THREAD

**Issue by jaap3** [cfpb/django-nudge#50]
As far as I can figure out it seems impossible to update files using nudge. With that I mean that models containing files get synced correctly, but the actual files do not get synced, resulting in missing files on the production environment.

Any plans/ideas on how to fix this?

**Comment by rosskarchner** [comment]
We know about that limitation, but haven't begun to figure out how to address it yet. We haven't needed it yet (or, have worked around it)

Nudge is somewhat inspired by a Wordpress plugin called 'RAMP'. In RAMP, when a batch is pushed, it sends the URL's of where those files live on staging, and the production server reaches back and fetches them via HTTP. I'm not sure I like that, because it means staging needs to be accessible to production (the way things work now, that isn't the case-- staging can happily live behind a NAT network).

But, I think the solutions boil down to:
- the 'RAMP' way
- including files in the encoded batch

Do you have an opinion on that?

**Comment by jaap3** [comment]
Including files in the encoded batch sounds great but could be problematic for large, or a large amount of files. It does however seems the most flexible way, for the reason you mentioned.
