### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by jezdez** [cfpb/django-nudge#59]
There are other countries out there that have no meaning for "public domain" as a software licensing model. Please choose an Open Source license. Github has this nifty license selector now: http://choosealicense.com

**Comment by regebro** [comment]
The closest you can get to public domain that actually works is CC0:

http://creativecommons.org/publicdomain/zero/1.0/

**Comment by rosskarchner** [comment]
I've been a part of a number of conversations about this very point ;) I don't think we don't have a choice when it comes to US users-- as a work by the US government, it can only by public domain. We might be able to dual-license it somehow, though.

**Comment by rosskarchner** [comment]
Sorry, didn't mean to close

**Comment by regebro** [comment]
The point is that public domain is not a license. So you don't need to dual-license it, you just need to license it. :-)

Saying that is is public domain has different meanings in different countries, and in some countries it has no meaning at all. As such this code is currently not open sourced or public domain in for example Germany. Including this project in a project in Germany would violate your copyright to the code. That you say that you don't want copyright makes no difference, distributing it in Germany would be illegal.

Therefore you need to have a license. 

Since it's US government code you are probably right, it has to bee public domain. I therefore strongly recommend CC0 in this case. I quote:

> this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.

This explicitly dedicates it to public domain, and also explains what that means. This means that in countries where "public domain" is meaningless, you have still waived your rights under copyright law. Distributing the code in Germany would now be perfectly fine.

I believe using CC0 satisfies both the government requirement of making it public domain, and the international requirements of explicitly explaining the terms. All you need to do for this is to include a copy of the full legal text (http://creativecommons.org/publicdomain/zero/1.0/legalcode) in a file called LICENSE.txt. Mentioning it in the README would also be good.
